"use client";

import React, { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

interface FAQItem {
  question: string;
  answer: string;
}

interface FAQCategory {
  title: string;
  items: FAQItem[];
}

const faqData: FAQCategory[] = [
{
  title: "General",
  items: [
  {
    question: "What is Piepio?",
    answer: "Piepio is an AI-powered fullstack engineering assistant that helps you build, deploy, and scale applications at lightning speed by generating production-ready code from natural language descriptions."
  },
  {
    question: "Is it really 100x faster?",
    answer: "Yes, by automating the boilerplate, architecture setup, and integration code, developers can focus on core logic and ship features in hours instead of days."
  },
  {
    question: "Can I use my own database?",
    answer: "Absolutely. Piepio supports various database adapters including PostgreSQL, MongoDB, and MySQL, allowing you to connect to your existing infrastructure seamlessly."
  }]

},
{
  title: "Technical",
  items: [
  {
    question: "Can I export the code?",
    answer: "Yes, all code generated by Piepio is yours. You can export the entire codebase at any time, and it follows standard project structures so you can continue development manually if you wish."
  }]

}];


const AccordionItem = ({
  item,
  isOpen,
  onClick,
  isLast





}: {item: FAQItem;isOpen: boolean;onClick: () => void;isLast?: boolean;}) => {
  return (
    <div className={cn(
      "border-b border-border transition-all duration-200",
      isLast && "border-b-0"
    )}>
      <button
        onClick={onClick}
        className="w-full py-6 flex items-center justify-between text-left group">

        <span className="text-[16px] font-semibold text-black tracking-tight group-hover:text-primary transition-colors !whitespace-pre-line">
          {item.question}
        </span>
        <ChevronDown
          className={cn(
            "w-4 h-4 text-black/30 transition-transform duration-300",
            isOpen && "rotate-180 text-primary"
          )} />

      </button>
      <div
        className={cn(
          "grid transition-all duration-300 ease-in-out overflow-hidden",
          isOpen ? "grid-rows-[1fr] opacity-100 pb-6" : "grid-rows-[0fr] opacity-0"
        )}>

        <div className="overflow-hidden">
          <p className="text-[15px] leading-relaxed text-muted-foreground max-w-[90%] !whitespace-pre-line">
            {item.answer}
          </p>
        </div>
      </div>
    </div>);

};

export default function FAQSection() {
  const [openItems, setOpenItems] = useState<Record<string, number | null>>({});

  const toggleItem = (categoryIndex: number, itemIndex: number) => {
    setOpenItems((prev) => ({
      ...prev,
      [categoryIndex]: prev[categoryIndex] === itemIndex ? null : itemIndex
    }));
  };

  return (
    <section id="faq" className="relative py-24 md:py-32 bg-white">
      {/* Container with background grid-like borders from design system */}
      <div className="container mx-auto max-w-[1314px] px-6 lg:px-14 relative">
        
        {/* Section Header */}
        <div className="max-w-[800px] mb-20">
          <h2 className="text-3xl md:text-[48px] font-bold tracking-tight text-black mb-6">
            Frequently asked <span className="text-primary">questions</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Everything you need to know about building with Piepio.
          </p>
        </div>

        {/* FAQ List organized by categories */}
        <div className="space-y-16 max-w-[900px]">
          {faqData.map((category, catIdx) =>
          <div key={category.title} className="relative">
              {/* Category Header with technical minimalist divider */}
              <div className="flex items-center gap-4 mb-8">
                <h3 className="text-[18px] font-bold text-black shrink-0">
                  {category.title}
                </h3>
                <div className="h-[1px] w-full bg-border" />
              </div>

              {/* Accordion Container */}
              <div className="bg-white rounded-xl border border-border overflow-hidden shadow-sm">
                <div className="px-6 md:px-8">
                  {category.items.map((item, itemIdx) =>
                <AccordionItem
                  key={item.question}
                  item={item}
                  isOpen={openItems[catIdx] === itemIdx}
                  onClick={() => toggleItem(catIdx, itemIdx)}
                  isLast={itemIdx === category.items.length - 1} />

                )}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Subtle Decorative Elements (Status Tags/Labels consistent with high level design) */}
        <div className="absolute top-0 right-14 hidden xl:block">
          <div className="mono-label text-[10px] opacity-20 rotate-90 origin-top-right">
            [ FAQ_MODULE_V1.0 ]
          </div>
        </div>
      </div>

      {/* Grid line accents consistent with hero/pricing sections */}
      <div className="absolute inset-0 pointer-events-none z-0">
        <div className="container relative h-full">
          <div className="absolute inset-y-0 left-0 w-[1px] bg-border opacity-30"></div>
          <div className="absolute inset-y-0 right-0 w-[1px] bg-border opacity-30"></div>
          <div className="absolute inset-y-0 left-1/2 w-[1px] bg-border opacity-10"></div>
        </div>
      </div>
    </section>);

}