import React from 'react';
import Navbar from "@/components/sections/navbar";
import Footer from "@/components/sections/footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />
      <div className="container mx-auto max-w-4xl px-6 py-20">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-12 italic">Last updated: {new Date().toLocaleDateString()}</p>
        
        <div className="prose dark:prose-invert max-w-none space-y-12">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Piepio (the "Service"), provided by Piepio Inc. ("we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">2. Use of Service</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Piepio provides an AI-powered development platform. You are granted a non-exclusive, non-transferable, revocable license to access and use the Service strictly in accordance with these terms.
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
              <li>You must be at least 13 years old to use this Service.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You may not use the Service for any illegal or unauthorized purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">3. User Accounts & Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              To access certain features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">4. Intellectual Property</h2>
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                <strong>Your Content:</strong> You retain all rights to the code and content generated by you using Piepio.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                <strong>Our Property:</strong> The Service, including its original content, features, and functionality, are and will remain the exclusive property of Piepio Inc. and its licensors.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">5. Prohibited Activities</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium; (ii) using any automated system, including "robots," "spiders," or "offline readers," to access the Service; (iii) attempting to interfere with the servers or networks connected to the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">6. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              In no event shall Piepio Inc., nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-primary">8. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            </p>
          </section>

          <section className="pt-8 border-t border-border">
            <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
            <p className="text-muted-foreground">
              If you have any questions about these Terms, please contact us at <span className="text-primary underline">legal@piepio.com</span>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
